# Generated by Django 3.2.2 on 2021-05-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Narrator', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('UploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('UploadTime', models.DateTimeField(auto_now_add=True)),
                ('Host', models.CharField(max_length=100)),
                ('Participants', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('SongDuration', models.DurationField()),
                ('UploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
